/**
 * Remotion Root — registers all compositions.
 * EventReel is the primary composition generated by the pipeline.
 */
import React from 'react';
import { Composition } from 'remotion';
import { EventReel } from './EventReel';

// Default values — overridden by the generated EventReel.tsx
const DEFAULT_FPS = 30;
const DEFAULT_DURATION_FRAMES = 900; // 30 seconds placeholder
const DEFAULT_WIDTH = 1920;
const DEFAULT_HEIGHT = 1080;

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="EventReel"
        component={EventReel}
        durationInFrames={DEFAULT_DURATION_FRAMES}
        fps={DEFAULT_FPS}
        width={DEFAULT_WIDTH}
        height={DEFAULT_HEIGHT}
      />
    </>
  );
};
